package jp.macs.workweb.domain.repository.bibleManage.project;

import java.util.List;

import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

import jp.macs.workweb.domain.entity.bibleManage.project.Project;
import jp.macs.workweb.domain.entity.bibleManage.project.ProjectCriteria;

@Mapper
public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    @SelectProvider(type=ProjectSqlProvider.class, method="countByExample")
    long countByExample(ProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    @DeleteProvider(type=ProjectSqlProvider.class, method="deleteByExample")
    int deleteByExample(ProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    @Delete({
        "delete from project",
        "where project_id = #{projectId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    @Insert({
        "insert into project (project_id, project_name, ",
        "staff, release_date)",
        "values (#{projectId,jdbcType=VARCHAR}, #{projectName,jdbcType=VARCHAR}, ",
        "#{staff,jdbcType=VARCHAR}, #{releaseDate,jdbcType=DATE})"
    })
    int insert(Project row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    @InsertProvider(type=ProjectSqlProvider.class, method="insertSelective")
    int insertSelective(Project row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    @SelectProvider(type=ProjectSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="project_id", property="projectId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="project_name", property="projectName", jdbcType=JdbcType.VARCHAR),
        @Result(column="staff", property="staff", jdbcType=JdbcType.VARCHAR),
        @Result(column="release_date", property="releaseDate", jdbcType=JdbcType.DATE)
    })
    List<Project> selectByExample(ProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    @Select({
        "select",
        "project_id, project_name, staff, release_date",
        "from project",
        "where project_id = #{projectId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="project_id", property="projectId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="project_name", property="projectName", jdbcType=JdbcType.VARCHAR),
        @Result(column="staff", property="staff", jdbcType=JdbcType.VARCHAR),
        @Result(column="release_date", property="releaseDate", jdbcType=JdbcType.DATE)
    })
    Project selectByPrimaryKey(String projectId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    @UpdateProvider(type=ProjectSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("row") Project row, @Param("example") ProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    @UpdateProvider(type=ProjectSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("row") Project row, @Param("example") ProjectCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    @UpdateProvider(type=ProjectSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Project row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    @Update({
        "update project",
        "set project_name = #{projectName,jdbcType=VARCHAR},",
          "staff = #{staff,jdbcType=VARCHAR},",
          "release_date = #{releaseDate,jdbcType=DATE}",
        "where project_id = #{projectId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(Project row);
}