package jp.macs.workweb.domain.entity.bibleManage.pullpush;

import java.io.Serializable;
import java.util.Date;

public class Files implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column files.file_id
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	private Integer fileId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column files.folder_id
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	private Integer folderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column files.file_name
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	private String fileName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column files.create_date
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table files
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column files.file_id
	 * @return  the value of files.file_id
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	public Integer getFileId() {
		return fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column files.file_id
	 * @param fileId  the value for files.file_id
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	public void setFileId(Integer fileId) {
		this.fileId = fileId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column files.folder_id
	 * @return  the value of files.folder_id
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	public Integer getFolderId() {
		return folderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column files.folder_id
	 * @param folderId  the value for files.folder_id
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	public void setFolderId(Integer folderId) {
		this.folderId = folderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column files.file_name
	 * @return  the value of files.file_name
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	public String getFileName() {
		return fileName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column files.file_name
	 * @param fileName  the value for files.file_name
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	public void setFileName(String fileName) {
		this.fileName = fileName == null ? null : fileName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column files.create_date
	 * @return  the value of files.create_date
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column files.create_date
	 * @param createDate  the value for files.create_date
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}