package jp.macs.workweb.domain.entity.bibleManage.pullpush;

import java.io.Serializable;
import java.util.Date;

public class Folders implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column folders.folder_id
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	private Integer folderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column folders.folder_name
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	private String folderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column folders.create_date
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	private Date createDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table folders
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column folders.folder_id
	 * @return  the value of folders.folder_id
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	public Integer getFolderId() {
		return folderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column folders.folder_id
	 * @param folderId  the value for folders.folder_id
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	public void setFolderId(Integer folderId) {
		this.folderId = folderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column folders.folder_name
	 * @return  the value of folders.folder_name
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	public String getFolderName() {
		return folderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column folders.folder_name
	 * @param folderName  the value for folders.folder_name
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	public void setFolderName(String folderName) {
		this.folderName = folderName == null ? null : folderName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column folders.create_date
	 * @return  the value of folders.create_date
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	public Date getCreateDate() {
		return createDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column folders.create_date
	 * @param createDate  the value for folders.create_date
	 * @mbg.generated  Tue Jan 24 22:24:03 JST 2023
	 */
	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}
}