package jp.macs.workweb.domain.entity.user;

import java.io.Serializable;
import java.util.Collection;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;

public class Users implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.id
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.password
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.name
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.mailaddress
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	private String mailaddress;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column users.role_id
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table users
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.id
	 * @return  the value of users.id
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.id
	 * @param id  the value for users.id
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.password
	 * @return  the value of users.password
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.password
	 * @param password  the value for users.password
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.name
	 * @return  the value of users.name
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.name
	 * @param name  the value for users.name
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.mailaddress
	 * @return  the value of users.mailaddress
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	public String getMailaddress() {
		return mailaddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.mailaddress
	 * @param mailaddress  the value for users.mailaddress
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	public void setMailaddress(String mailaddress) {
		this.mailaddress = mailaddress == null ? null : mailaddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column users.role_id
	 * @return  the value of users.role_id
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column users.role_id
	 * @param roleId  the value for users.role_id
	 * @mbg.generated  Wed Jan 25 21:34:43 JST 2023
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	

}