package jp.macs.workweb.domain.repository.bibleManage.pullpush;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.jdbc.SQL;

import jp.macs.workweb.domain.entity.bibleManage.pullpush.Pullpush;
import jp.macs.workweb.domain.entity.bibleManage.pullpush.PullpushCriteria;
import jp.macs.workweb.domain.entity.bibleManage.pullpush.PullpushCriteria.Criteria;
import jp.macs.workweb.domain.entity.bibleManage.pullpush.PullpushCriteria.Criterion;

public class PullpushSqlProvider {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pullpush
     *
     * @mbg.generated Sun Jan 22 15:04:47 JST 2023
     */
    public String countByExample(PullpushCriteria example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("pullpush");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pullpush
     *
     * @mbg.generated Sun Jan 22 15:04:47 JST 2023
     */
    public String deleteByExample(PullpushCriteria example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("pullpush");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pullpush
     *
     * @mbg.generated Sun Jan 22 15:04:47 JST 2023
     */
    public String insertSelective(Pullpush row) {
        SQL sql = new SQL();
        sql.INSERT_INTO("pullpush");
        
        if (row.getPullpushId() != null) {
            sql.VALUES("pullpush_id", "#{pullpushId,jdbcType=INTEGER}");
        }
        
        if (row.getEachDocId() != null) {
            sql.VALUES("each_doc_id", "#{eachDocId,jdbcType=INTEGER}");
        }
        
        if (row.getFileId() != null) {
            sql.VALUES("file_id", "#{fileId,jdbcType=INTEGER}");
        }
        
        if (row.getFolderId() != null) {
            sql.VALUES("folder_id", "#{folderId,jdbcType=INTEGER}");
        }
        
        if (row.getProjectId() != null) {
            sql.VALUES("project_id", "#{projectId,jdbcType=INTEGER}");
        }
        
        if (row.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=INTEGER}");
        }
        
        if (row.getPulledDate() != null) {
            sql.VALUES("pulled_date", "#{pulledDate,jdbcType=DATE}");
        }
        
        if (row.getPushedDate() != null) {
            sql.VALUES("pushed_date", "#{pushedDate,jdbcType=DATE}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pullpush
     *
     * @mbg.generated Sun Jan 22 15:04:47 JST 2023
     */
    public String selectByExample(PullpushCriteria example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("pullpush_id");
        } else {
            sql.SELECT("pullpush_id");
        }
        sql.SELECT("each_doc_id");
        sql.SELECT("file_id");
        sql.SELECT("folder_id");
        sql.SELECT("project_id");
        sql.SELECT("status");
        sql.SELECT("pulled_date");
        sql.SELECT("pushed_date");
        sql.FROM("pullpush");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pullpush
     *
     * @mbg.generated Sun Jan 22 15:04:47 JST 2023
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        Pullpush row = (Pullpush) parameter.get("row");
        PullpushCriteria example = (PullpushCriteria) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("pullpush");
        
        if (row.getPullpushId() != null) {
            sql.SET("pullpush_id = #{row.pullpushId,jdbcType=INTEGER}");
        }
        
        if (row.getEachDocId() != null) {
            sql.SET("each_doc_id = #{row.eachDocId,jdbcType=INTEGER}");
        }
        
        if (row.getFileId() != null) {
            sql.SET("file_id = #{row.fileId,jdbcType=INTEGER}");
        }
        
        if (row.getFolderId() != null) {
            sql.SET("folder_id = #{row.folderId,jdbcType=INTEGER}");
        }
        
        if (row.getProjectId() != null) {
            sql.SET("project_id = #{row.projectId,jdbcType=INTEGER}");
        }
        
        if (row.getStatus() != null) {
            sql.SET("status = #{row.status,jdbcType=INTEGER}");
        }
        
        if (row.getPulledDate() != null) {
            sql.SET("pulled_date = #{row.pulledDate,jdbcType=DATE}");
        }
        
        if (row.getPushedDate() != null) {
            sql.SET("pushed_date = #{row.pushedDate,jdbcType=DATE}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pullpush
     *
     * @mbg.generated Sun Jan 22 15:04:47 JST 2023
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("pullpush");
        
        sql.SET("pullpush_id = #{row.pullpushId,jdbcType=INTEGER}");
        sql.SET("each_doc_id = #{row.eachDocId,jdbcType=INTEGER}");
        sql.SET("file_id = #{row.fileId,jdbcType=INTEGER}");
        sql.SET("folder_id = #{row.folderId,jdbcType=INTEGER}");
        sql.SET("project_id = #{row.projectId,jdbcType=INTEGER}");
        sql.SET("status = #{row.status,jdbcType=INTEGER}");
        sql.SET("pulled_date = #{row.pulledDate,jdbcType=DATE}");
        sql.SET("pushed_date = #{row.pushedDate,jdbcType=DATE}");
        
        PullpushCriteria example = (PullpushCriteria) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pullpush
     *
     * @mbg.generated Sun Jan 22 15:04:47 JST 2023
     */
    protected void applyWhere(SQL sql, PullpushCriteria example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}