package jp.macs.workweb.domain.entity.bibleManage.project;

import java.io.Serializable;
import java.sql.Date;






public class Project implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_id
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    private String projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.project_name
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.staff
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    private String staff;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column project.release_date
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    private Date releaseDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table project
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_id
     *
     * @return the value of project.project_id
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_id
     *
     * @param projectId the value for project.project_id
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.project_name
     *
     * @return the value of project.project_name
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.project_name
     *
     * @param projectName the value for project.project_name
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.staff
     *
     * @return the value of project.staff
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    public String getStaff() {
        return staff;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.staff
     *
     * @param staff the value for project.staff
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    public void setStaff(String staff) {
        this.staff = staff == null ? null : staff.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column project.release_date
     *
     * @return the value of project.release_date
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    public Date getReleaseDate() {
        return releaseDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column project.release_date
     *
     * @param releaseDate the value for project.release_date
     *
     * @mbg.generated Wed Jan 18 20:35:13 JST 2023
     */
    public void setReleaseDate(Date releaseDate) {
        this.releaseDate = releaseDate;
    }
}